### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by bioinfor-123** [LMSE/CmpdEnzymPred#1]
I downloaded "CmpdEnzymPred" from github, but found it can't run (from W_phosphatase_att.ipynb), because some files are missing, such as "Y04E_all_X_y.p" .

**Comment by Zhiqing-Xu** [comment]
This file (W_phosphatase_att.ipynb) is just for test use and was uploaded by mistake I think. It has nothing to do with the main part of the prediction pipeline. Sequence Pooling based on attention is beyond the scope of this paper but is still interested. We were testing attention mechanism as a potential alternative to the convolutional pooling idea but unfortunately found that it didn't get a substantial improvement as we expected.

**Comment by bioinfor-123** [comment]
Thank you for your reply. I did not find any input files of the study, could your upload them? Or else, we can't run the program of python.

**Comment by Zhiqing-Xu** [comment]
In the paper, we have tested the prediction performance of the new pipeline with different datasets obtained from _"Machine learning modeling of family wide enzyme-substrate specificity screens"_ (arXiv:2109.03900v1, by S. Goldman and C.W. Coley). I have uploaded the phosphatase data files for you to test the code without changing anything of the code.

**Comment by Zhiqing-Xu** [comment]
>
